{
 "title": "Validator",
 "description": "Loki dashboard with quick search and timeline.",
 "tags": [
  "kroma",
  "validator"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Validator Image",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kroma_validator_default_info",
     "legendFormat": "kromanetwork/validator:{{version}}"
    }
   ]
  },
  {
   "title": "Current Nonce",
   "type": "stat",
   "description": "Current nonce of the validator account you specified in the .env file(KROMA_VALIDATOR__MNEMONIC, KROMA_VALIDATOR__HD_PATH, KROMA_VALIDATOR__PRIVATE_KEY)",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kroma_validator_default_txmgr_current_nonce",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Submit Count Total",
   "type": "stat",
   "description": "The total number of outputs submitted to the L1 by your validator node (This metric will appear after the output is submitted)",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kroma_validator_default_confirm_total{status=\"failed\"} + kroma_validator_default_confirm_total{status=\"success\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Submit Count Success",
   "type": "stat",
   "description": "The number of success outputs submitted to the L1 by your validator node (This metric will appear after the output is submitted)",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kroma_validator_default_confirm_total{status=\"success\"}"
    }
   ]
  },
  {
   "title": "Output Submit Count Failed",
   "type": "stat",
   "description": "The number of failed outputs submitted to the L1 by your validator node (This metric will appear after the output is submitted)",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kroma_validator_default_confirm_total{status=\"failed\"}"
    }
   ]
  },
  {
   "title": "Account Balance",
   "type": "stat",
   "description": "\t\nETH balance of the validator specified in the .env file(KROMA_VALIDATOR__MNEMONIC, KROMA_VALIDATOR__HD_PATH, KROMA_VALIDATOR__PRIVATE_KEY)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kroma_validator_default_balance",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Validator Deposit Amount",
   "type": "stat",
   "description": "The balance of deposited ETH for validator",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kroma_validator_default_deposit_amount",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Validator Status",
   "type": "stat",
   "description": "\"Healthy' if the kroma-validator has finished starting up",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kroma_validator_default_up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "L1 RPC Error Count",
   "type": "timeseries",
   "description": "Count of L1 RPC errors(ex. timeouts) in transaction manager that have occurred from the endpoint that you specified in the .env file(KROMA_VALIDATOR__L1_RPC_ENDPOINT)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kroma_validator_default_txmgr_rpc_error_count",
     "legendFormat": "kroma-validator"
    }
   ]
  }
 ]
}